### ISSUE TITLE
Feedback in development branch

### ISSUE THREAD

**Issue by lpantano** [bcbio/bcbioR#28]
Notes about bcbioR process
https://github.com/bcbio/bcbioR
“Set base project” and “Set RNAseq report folder” code do the same thing in terms of setting up file structure and RMD, this is confusing
Link to vignette is missing a “ and then does not work
Steps followed (based on ReadMe)
Skipped everything before “Downstream analysis” because Emma already did this
Modify “information.R”
Modify “QC/QC_nf-core.Rmd” and “params_qc_nf-core.R” because we are running nf-core output template
Make sure all the libraries listed in “QC_nf-core.Rmd” are installed
Knit “QC_nf-core.Rmd”
Create additional plots / colors / descriptions in QC report as needed
In QC_nf-core.Rmd
“load_metadata” chunk removes fastq and strandedness columns twice
Some typos
In “source_params” chunk, “manually” is misspelled
In “prepare metrics” chunk, “General Table of MultiQC” is misspelled
In “Read Metrics” section, all plots have “size=4” in geom_point call except for “tRNA/rRNA mapping rate”
In “PCA” section, the code indicates that PCs 1-5 should be assessed, but only looks at 1-4
Also, would be nice to give examples/options here for adding additional coloring/shapes to PCA plots (other metadata besides factor of interest)
Colors not consistent between heat map and other figures (everything else is yellow/blue, heat map is grey/black)
In “plot_genes_detected” chunk, title of second plot is “Total reads” rather than “Number of genes”

**Comment by abartlett004** [comment]
Notes about bcbioR process https://github.com/bcbio/bcbioR
- [ ] “Set base project” and “Set RNAseq report folder” code do the same thing in terms of setting up file structure and RMD, this is confusing
- [ ] Link to vignette is missing a “ and then does not work

Steps followed (based on ReadMe)

- Skipped everything before “Downstream analysis” because Emma already did this
- Modify “information.R”
- Modify “QC/QC_nf-core.Rmd” and “params_qc_nf-core.R” because we are running nf-core output template
- Make sure all the libraries listed in “QC_nf-core.Rmd” are installed
- Knit “QC_nf-core.Rmd”
- Create additional plots / colors / descriptions in QC report as needed

In QC_nf-core.Rmd
- [ ] “load_metadata” chunk removes fastq and strandedness columns twice

Some typos
- [ ] In “source_params” chunk, “manually” is misspelled
- [ ] In “prepare metrics” chunk, “General Table of MultiQC” is misspelled
- [ ] In “Read Metrics” section, all plots have “size=4” in geom_point call except for “tRNA/rRNA mapping rate”
- [ ] In “PCA” section, the code indicates that PCs 1-5 should be assessed, but only looks at 1-4

Other
- [ ] Also, would be nice to give examples/options here for adding additional coloring/shapes to PCA plots (other metadata besides factor of interest)
- [ ] Colors not consistent between heat map and other figures (everything else is yellow/blue, heat map is grey/black)
- [ ] In “plot_genes_detected” chunk, title of second plot is “Total reads” rather than “Number of genes”
